### ISSUE TITLE
Python environment

### ISSUE THREAD

**Issue by caitsimop** [SucreLab/LungDevelopment#2]
Thanks for all this hard work! 

I see there is already a request for the cell labels.

In addition, I'm interested in using your approach and your code. Would it be possible to having the conda environment that's called in your `helper_functions/libraries.R` file? (ie `use_python("~/anaconda3/envs/scseq/bin/python")`)

Thanks!

**Comment by nimne** [comment]
Hello! Sorry, I missed the comments in the github repo. I have recently updated the repo with a folder 'environment_info' that has the conda environment. While this file ended up having a ton of packages, the key packages are: python=3.8.5, cellrank=1.1.0, scanpy=1.8.1, and the pip-installed package: anndata==0.7.8'.

We're happy to send along a link to the processed Seurat objects. Could you please send me an email at nick.negretti@vumc.org and I am happy to provide a link!

**Comment by nimne** [comment]
Sent data link by email! Closing issue.
