### ISSUE TITLE
Cell label information

### ISSUE THREAD

**Issue by EddieLv** [SucreLab/LungDevelopment#3]
Excellent work!
I wanna use your dataset as a reference for my own data, could you provide me with the cell label of each cell in each time?
Thanks a lot! :)

**Comment by erzakiev** [comment]
I'd also like to have this information. This repo is of no help at all - even if I fork it to my computer it still references source data which is not downloaded with it, nor there are instructions on how to get it.

**Comment by nimne** [comment]
Sent data link by email! Closing issue.

**Comment by erzakiev** [comment]
Can you please send the link to me, too? I dropped you an email 5h ago
